AndyHardie fixes to login/phone
swxy/NoPixelServer pull request #6
Opened 2021-03-27 06:25 UTC by Adoggman

The Rare5M.co user AndyHardie posted a few fixes to cl_login.lua and the phone resource. The cl_login change fixes players being stuck and unable to move when they spawn.

2021-03-30 06:47 UTC, easytutz commented
SIR NOPIXEL.sql not working
![image](https://user-images.githubusercontent.com/79555211/112945354-9bf58400-914d-11eb-9e6f-df49f3ef29a4.png)

MYSQL SAID: #1062 - Duplicate entry '1' for key 'PRIMARY'

SQL QUERY ERROR:
INSERT INTO `characters` (`id`, `owner`, `first_name`, `last_name`, `date_created`, `dob`, `cash`, `bank`, `phone_number`, `story`, `new`, `deleted`, `gender`, `jail_time`, `dirty_money`, `gang_type`, `jail_time_mobster`, `judge_type`, `iswjob`, `metaData`, `stress_level`, `bones`, `emotes`, `paycheck`, `stocks`, `rehab`, `meta`, `dna`) VALUES	(1, 'steam:1100001113b37ba', 'Daniel', 'Walker', '2021-01-31 14:22:03', '1999-12-01', 2147483247, 5000, 4642225298, 'mr Sway cant think of name hes dumb', 1, 0, 0, 0, 0, 0, 00000000000, 0, 0, '{"hunger":25,"thrist":98,"health":200,"armour":0}', 600, '[{"offset1":0.35,"boneIndex":11816,"maxhit":false,"injuryType":4,"hitcount":0,"part":"Pelvis","applied":false,"zone":0,"offset2":0.35,"timer":0},{"offset1":0.35,"boneIndex":58271,"maxhit":false,"injuryType":4,"hitcount":0,"part":"Left Thigh","applied":false,"zone":4,"offset2":0.8,"timer":0},{"offset1":0.45,"boneIndex":47495,"maxhit":false,"injuryType":1,"hitcount":0,"part":"Mouth","applied":false,"zone":1,"offset2":0.35,"timer":0},{"offset1":0.35,"boneIndex":14201,"maxhit":true,"injuryType":1,"hitcount":0,"part":"Left Foot","applied":false,"zone":4,"offset2":0.2,"timer":0},{"offset1":0.35,"boneIndex":46078,"maxhit":false,"injuryType":4,"hitcount":0,"part":"Left Knee","applied":false,"zone":4,"offset2":0.55,"timer":0},{"offset1":0.35,"boneIndex":51826,"maxhit":false,"injuryType":4,"hitcount":0,"part":"Right Thigh","applied":false,"zone":5,"offset2":0.8,"timer":0},{"offset1":0.25,"boneIndex":24816,"maxhit":false,"injuryType":5,"hitcount":0,"part":"Spine Lower","applied":false,"zone":0,"offset2":0.35,"timer":0},{"offset1":0.35,"boneIndex":52301,"maxhit":true,"injuryType":1,"hitcount":0,"part":"Right Foot","applied":false,"zone":5,"offset2":0.2,"timer":0},{"offset1":0.35,"boneIndex":16335,"maxhit":false,"injuryType":4,"hitcount":0,"part":"Right Knee","applied":false,"zone":5,"offset2":0.55,"timer":0},{"offset1":0.25,"boneIndex":24817,"maxhit":false,"injuryType":5,"hitcount":0,"part":"Spine Mid","applied":false,"zone":0,"offset2":0.55,"timer":0},{"offset1":0.35,"boneIndex":60309,"maxhit":true,"injuryType":1,"hitcount":0,"part":"Left Hand","applied":false,"zone":2,"offset2":0.2,"timer":0},{"offset1":0.35,"boneIndex":22711,"maxhit":false,"injuryType":3,"hitcount":0,"part":"Left Elbow","applied":false,"zone":2,"offset2":0.75,"timer":0},{"offset1":0.35,"boneIndex":57005,"maxhit":true,"injuryType":1,"hitcount":0,"part":"Right Hand","applied":false,"zone":3,"offset2":0.2,"timer":0},{"offset1":0.35,"boneIndex":2992,"maxhit":false,"injuryType":3,"hitcount":0,"part":"Right Elbow","applied":false,"zone":3,"offset2":0.75,"timer":0},{"offset1":0.25,"boneIndex":39317,"maxhit":false,"injuryType":5,"hitcount":0,"part":"Neck","applied":false,"zone":0,"offset2":0.95,"timer":0},{"offset1":0.35,"boneIndex":31086,"maxhit":false,"injuryType":2,"hitcount":0,"part":"Head","applied":false,"zone":1,"offset2":0.75,"timer":0},{"offset1":0.25,"boneIndex":24818,"maxhit":false,"injuryType":5,"hitcount":0,"part":"Spine High","applied":false,"zone":0,"offset2":0.85,"timer":0},{"offset1":0.15,"boneIndex":64729,"maxhit":false,"injuryType":3,"hitcount":0,"part":"Left Clavicle","applied":false,"zone":0,"offset2":0.75,"timer":0},{"offset1":0.35,"boneIndex":26610,"maxhit":true,"injuryType":1,"hitcount":0,"part":"Left Finger Pinky","applied":false,"zone":2,"offset2":0.2,"timer":0},{"offset1":0.35,"boneIndex":26611,"maxhit":true,"injuryType":1,"hitcount":0,"part":"Left Finger Index","applied":false,"zone":2,"offset2":0.2,"timer":0},{"offset1":0.35,"boneIndex":26612,"maxhit":true,"injuryType":1,"hitcount":0,"part":"Left Finger Middle","applied":false,"zone":2,"offset2":0.2,"timer":0},{"offset1":0.35,"boneIndex":26613,"maxhit":true,"injuryType":1,"hitcount":0,"part":"Left Finger Ring","applied":false,"zone":2,"offset2":0.2,"timer":0},{"offset1":0.35,"boneIndex":26614,"maxhit":true,"injuryType":1,"hitcount":0,"part":"Left Finger Thumb","applied":false,"zone":2,"offset2":0.2,"timer":0},{"offset1":0.35,"boneIndex":10706,"maxhit":false,"injuryType":3,"hitcount":0,"part":"Right Clavicle","applied":false,"zone":0,"offset2":0.75,"timer":0},{"offset1":0.35,"boneIndex":58866,"maxhit":true,"injuryType":1,"hitcount":0,"part":"Right Finger Pinky","applied":false,"zone":3,"offset2":0.2,"timer":0},{"offset1":0.35,"boneIndex":58867,"maxhit":true,"injuryType":1,"hitcount":0,"part":"Right Finger Index","applied":false,"zone":3,"offset2":0.2,"timer":0},{"offset1":0.35,"boneIndex":58868,"maxhit":true,"injuryType":1,"hitcount":0,"part":"Right Finger Middle","applied":false,"zone":3,"offset2":0.2,"timer":0},{"offset1":0.35,"boneIndex":58869,"maxhit":true,"injuryType":1,"hitcount":0,"part":"Right Finger Ring","applied":false,"zone":3,"offset2":0.2,"timer":0},{"offset1":0.35,"boneIndex":58870,"maxhit":true,"injuryType":1,"hitcount":0,"part":"Right Finger Thumb","applied":false,"zone":3,"offset2":0.2,"timer":0},{"offset1":0.55,"boneIndex":21550,"maxhit":false,"injuryType":1,"hitcount":0,"part":"Face Left CheekBone","applied":false,"zone":1,"offset2":0.45,"timer":0},{"offset1":0.35,"boneIndex":19336,"maxhit":false,"injuryType":1,"hitcount":0,"part":"Face Right CheekBone","applied":false,"zone":1,"offset2":0.45,"timer":0},{"offset1":0.45,"boneIndex":37193,"maxhit":false,"injuryType":2,"hitcount":0,"part":"Forehead","applied":false,"zone":1,"offset2":0.75,"timer":0},{"offset1":0.45,"boneIndex":61839,"maxhit":true,"injuryType":1,"hitcount":0,"part":"Face UpperLip","applied":false,"zone":1,"offset2":0.35,"timer":0},{"offset1":0.45,"boneIndex":20623,"maxhit":true,"injuryType":1,"hitcount":0,"part":"Face LowerLip","applied":false,"zone":1,"offset2":0.35,"timer":0}]', '{}', 6520, '[{"value":3.0},{"value":0.0},{"value":0.0},{"value":0.0},{"value":0.0},{"value":0.0}]', 0, '"move_m@gangster@var_e"', '{}'),	(17, 'steam:11000011d73b356', 'John', 'Richard', '2021-01-30 01:16:59', '2000-01-01', 15, 3750, 7565964384, 'Character\'s background, this can be short and simple', 1, 0, 0, 0, 0, 0, 00000000000, 0, 0, '{"armour":0,"hunger":82,"thrist":90,"health":180}', 774, '[{"maxhit":false,"part":"Pelvis","boneIndex":11816,"timer":0,"applied":false,"offset2":0.35,"hitcount":0,"offset1":0.35,"injuryType":4,"zone":0},{"maxhit":false,"part":"Left Thigh","boneIndex":58271,"timer":0,"applied":false,"offset2":0.8,"hitcount":0,"offset1":0.35,"injuryType":4,"zone":4},{"maxhit":false,"part":"Mouth","boneIndex":47495,"timer":0,"applied":false,"offset2":0.35,"hitcount":0,"offset1":0.45,"injuryType":1,"zone":1},{"maxhit":true,"part":"Left Foot","boneIndex":14201,"timer":0,"applied":false,"offset2":0.2,"hitcount":0,"offset1":0.35,"injuryType":1,"zone":4},{"maxhit":false,"part":"Left Knee","boneIndex":46078,"timer":0,"applied":false,"offset2":0.55,"hitcount":0,"offset1":0.35,"injuryType":4,"zone":4},{"maxhit":false,"part":"Right Thigh","boneIndex":51826,"timer":0,"applied":false,"offset2":0.8,"hitcount":0,"offset1":0.35,"injuryType":4,"zone":5},{"maxhit":false,"part":"Spine Lower","boneIndex":24816,"timer":0,"applied":false,"offset2":0.35,"hitcount":0,"offset1":0.25,"injuryType":5,"zone":0},{"maxhit":true,"part":"Right Foot","boneIndex":52301,"timer":0,"applied":false,"offset2":0.2,"hitcount":0,"offset1":0.35,"injuryType":1,"zone":5},{"maxhit":false,"part":"Right Knee","boneIndex":16335,"timer":0,"applied":false,"offset2":0.55,"hitcount":0,"offset1":0.35,"injuryType":4,"zone":5},{"maxhit":false,"part":"Spine Mid","boneIndex":24817,"timer":0,"applied":false,"offset2":0.55,"hitcount":0,"offset1":0.25,"injuryType":5,"zone":0},{"maxhit":true,"part":"Left Hand","boneIndex":60309,"timer":0,"applied":false,"offset2":0.2,"hitcount":0,"offset1":0.35,"injuryType":1,"zone":2},{"maxhit":false,"part":"Left Elbow","boneIndex":22711,"timer":0,"applied":false,"offset2":0 [...]

2021-03-30 20:47 UTC, Adoggman commented
> SIR NOPIXEL.sql not working
> ![image](https://user-images.githubusercontent.com/79555211/112945354-9bf58400-914d-11eb-9e6f-df49f3ef29a4.png)
> 
> `MYSQL SAID: #1062 - Duplicate entry '1' for key 'PRIMARY'`
 
`Duplicate entry '1' for key 'PRIMARY'` means it's trying to add a row to a table that already exists. Did you run this twice? Try deleting all rows and/or dropping all the tables and running it again.

2021-04-01 11:13 UTC, LiamMC534 commented
anybody know how to find item id, im trying to find a taser cartridge

2021-04-01 14:55 UTC, Aniket999969 commented
how to use e-blips for pd and ems please :)

2021-04-02 09:06 UTC, Adoggman commented
Guys, I can't help anyone at this point and I won't be able to for a while. I haven't been able to get the server up and running properly yet myself. I'm going to keep updating this repository so you don't have to fix everything I have, but what you see here is as far as I've gotten.

Please add your own fixes as you do them, or at least message me your fixes.

2021-04-02 09:07 UTC, Aniket999969 commented
how to use e-blips and job whitelisting please tell @Adoggman

2021-04-02 09:53 UTC, Aniket999969 commented
np-voice fix?

2021-04-03 12:44 UTC, LiamMC534 commented
suggestion for fix: taser cartridge reloading but not allowing taser to shoot

2021-04-03 15:02 UTC, Aniket999969 commented
Yo Please Help i want to know how to use np-eblips please help anyone

2021-04-03 19:59 UTC, EliasMatta commented
I'm soo happy you are fixing the issues also i  just want to tell you more stuff in-case you want to fix such as  there are major issues with invisible objects in Courthouse and also in the houses that generate for house robberies and the house robberies don't work we don't get any items

2021-04-03 20:23 UTC, Josephsgithub commented
anyone else have problems with doors

2021-04-03 20:33 UTC, Adoggman commented
Again, I have not gotten farther than what you see here. I do not know how to get eblips to work and have no idea about the courthouse or robberies. This is not a place to suggest fixes or ask for help yet. If you are struggling to get this to work and have no experience with coding, you are not going to get far. My END goal is to have it working WITHOUT needing to know code, but I'm probably 2% done. I will no longer respond to anyone asking for help. I will try to get GitHub issues to work so you can report error messages at some point. On Sat, Apr 3, 2021 at 3:23 PM,             Josephsgithub ***@***.***> wrote:
anyone else have problems with doors

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/swxy/NoPixelServer/pull/6#issuecomment-812920693",
"url": "https://github.com/swxy/NoPixelServer/pull/6#issuecomment-812920693",
"name": "View Pull Request"
},
"description": "View this Pull Request on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

2021-04-04 10:07 UTC, Adoggman commented
If you have issues go [here](https://github.com/Adoggman/NoPixelServer/issues).

2021-04-06 03:35 UTC, radcrazykid2 requested changes
you fixed the move only with ALT pressed but broke character switch. cant switch characters at prison or hospital now. have to close game completely. any idea how to fix that?

2021-04-06 03:47 UTC, Adoggman commented
Not sure. Like I said above, open an issue on my repository. 

2021-04-06 18:36 UTC, merged